// <auto-generated />
using System;
using EnvanterServisi.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnvanterServisi.Api.Data.Migrations
{
    [DbContext(typeof(EnvanterDbContext))]
    partial class EnvanterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("envanter")
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnvanterServisi.Api.Domain.Entities.Cihaz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("AssetTag")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("EldenCikarmaAciklamasi")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EldenCikarmaTipi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateOnly?>("EnvanterdenCikisTarihi")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EnvantereGirisTarihi")
                        .HasColumnType("date");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KategoriId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LokasyonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SatilanKisiVeyaKurum")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("SeriNumarasi")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("ToplamVarligaDahilMi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AssetTag")
                        .IsUnique();

                    b.HasIndex("KategoriId");

                    b.HasIndex("LokasyonId");

                    b.HasIndex("SeriNumarasi")
                        .IsUnique();

                    b.ToTable("Cihazlar", "envanter", t =>
                        {
                            t.HasCheckConstraint("CK_Cihazlar_SeriNumarasi_Veya_AssetTag", "\"SeriNumarasi\" IS NOT NULL OR \"AssetTag\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("EnvanterServisi.Api.Domain.Entities.Kategori", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("KritikStokSeviyesi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UstKategoriId")
                        .HasColumnType("uuid");

                    b.Property<string>("VarlikTuru")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("UstKategoriId");

                    b.HasIndex("Ad", "UstKategoriId")
                        .IsUnique();

                    b.ToTable("Kategoriler", "envanter");
                });

            modelBuilder.Entity("EnvanterServisi.Api.Domain.Entities.KritikStokKurali", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("CihazModeli")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KategoriId")
                        .HasColumnType("uuid");

                    b.Property<int>("KritikStokSeviyesi")
                        .HasColumnType("integer");

                    b.Property<Guid>("LokasyonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LokasyonId", "KategoriId", "CihazModeli")
                        .IsUnique();

                    b.ToTable("KritikStokKurallari", "envanter");
                });

            modelBuilder.Entity("EnvanterServisi.Api.Domain.Entities.Lokasyon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UstLokasyonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UstLokasyonId");

                    b.HasIndex("Ad", "UstLokasyonId")
                        .IsUnique();

                    b.ToTable("Lokasyonlar", "envanter");
                });

            modelBuilder.Entity("EnvanterServisi.Api.Domain.Entities.SarfMalzeme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("EldekiMiktar")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KategoriId")
                        .HasColumnType("uuid");

                    b.Property<int>("KritikStokSeviyesi")
                        .HasColumnType("integer");

                    b.Property<Guid>("LokasyonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("LokasyonId");

                    b.HasIndex("Ad", "KategoriId", "LokasyonId")
                        .IsUnique();

                    b.ToTable("SarfMalzemeler", "envanter");
                });

            modelBuilder.Entity("EnvanterServisi.Api.Domain.Entities.StokHareketi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("CihazId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HareketTipi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("Miktar")
                        .HasColumnType("integer");

                    b.Property<string>("Neden")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("OlusturanKullaniciId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SarfMalzemeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("StokHareketleri", "envanter");
                });

            modelBuilder.Entity("EnvanterServisi.Api.Domain.Entities.Cihaz", b =>
                {
                    b.HasOne("EnvanterServisi.Api.Domain.Entities.Kategori", null)
                        .WithMany()
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnvanterServisi.Api.Domain.Entities.Lokasyon", null)
                        .WithMany()
                        .HasForeignKey("LokasyonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EnvanterServisi.Api.Domain.Entities.Kategori", b =>
                {
                    b.HasOne("EnvanterServisi.Api.Domain.Entities.Kategori", null)
                        .WithMany()
                        .HasForeignKey("UstKategoriId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EnvanterServisi.Api.Domain.Entities.Lokasyon", b =>
                {
                    b.HasOne("EnvanterServisi.Api.Domain.Entities.Lokasyon", null)
                        .WithMany()
                        .HasForeignKey("UstLokasyonId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EnvanterServisi.Api.Domain.Entities.SarfMalzeme", b =>
                {
                    b.HasOne("EnvanterServisi.Api.Domain.Entities.Kategori", null)
                        .WithMany()
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnvanterServisi.Api.Domain.Entities.Lokasyon", null)
                        .WithMany()
                        .HasForeignKey("LokasyonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
