services:
  postgres:
    image: postgres:16
    container_name: it-envanter-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: itenvanter
      POSTGRES_PASSWORD: itenvanter123
      POSTGRES_DB: it_envanter_takip
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: it-envanter-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
