services:
  postgres:
    image: postgres:16
    container_name: it-envanter-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: itenvanter
      POSTGRES_PASSWORD: itenvanter123
      POSTGRES_DB: it_envanter_takip
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: it-envanter-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo:7
    container_name: it-envanter-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: itenvanter
      MONGO_INITDB_ROOT_PASSWORD: itenvanter123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  postgres_data:
  mongodb_data:
