// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZimmetServisi.Api.Data;

#nullable disable

namespace ZimmetServisi.Api.Data.Migrations
{
    [DbContext(typeof(ZimmetDbContext))]
    [Migration("20260808163710_IlkZimmetSemasi")]
    partial class IlkZimmetSemasi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("zimmet")
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZimmetServisi.Api.Domain.Entities.Zimmet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CihazAd")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("CihazAssetTag")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("CihazId")
                        .HasColumnType("uuid");

                    b.Property<string>("CihazSeriNumarasi")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IadeAlanKullaniciId")
                        .HasColumnType("uuid");

                    b.Property<string>("IadeKontrolDurumu")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("IadeKontroluYapanKullaniciId")
                        .HasColumnType("uuid");

                    b.Property<string>("IadeNotu")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly?>("IadeTarihi")
                        .HasColumnType("date");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PersonelAdSoyad")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("PersonelEmail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("PersonelId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ZimmetTarihi")
                        .HasColumnType("date");

                    b.Property<Guid>("ZimmetleyenKullaniciId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CihazId")
                        .IsUnique()
                        .HasFilter("\"Durum\" IN ('Aktif', 'IadeSurecinde')");

                    b.HasIndex("Durum");

                    b.HasIndex("PersonelId");

                    b.ToTable("Zimmetler", "zimmet");
                });
#pragma warning restore 612, 618
        }
    }
}
