// <auto-generated />
using System;
using KimlikVePersonelServisi.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KimlikVePersonelServisi.Api.Data.Migrations
{
    [DbContext(typeof(KimlikPersonelDbContext))]
    partial class KimlikPersonelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("kimlik_personel")
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KimlikVePersonelServisi.Api.Domain.Entities.Departman", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SorumluPersonelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.HasIndex("SorumluPersonelId");

                    b.ToTable("Departmanlar", "kimlik_personel");
                });

            modelBuilder.Entity("KimlikVePersonelServisi.Api.Domain.Entities.Kullanici", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PersonelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.HasIndex("PersonelId")
                        .IsUnique();

                    b.ToTable("Kullanicilar", "kimlik_personel");
                });

            modelBuilder.Entity("KimlikVePersonelServisi.Api.Domain.Entities.Personel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<Guid>("DepartmanId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DepartmanSorumlusuMu")
                        .HasColumnType("boolean");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("IseGirisTarihi")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("IstenAyrilisTarihi")
                        .HasColumnType("date");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Personeller", "kimlik_personel");
                });

            modelBuilder.Entity("KimlikVePersonelServisi.Api.Domain.Entities.Departman", b =>
                {
                    b.HasOne("KimlikVePersonelServisi.Api.Domain.Entities.Personel", null)
                        .WithMany()
                        .HasForeignKey("SorumluPersonelId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("KimlikVePersonelServisi.Api.Domain.Entities.Kullanici", b =>
                {
                    b.HasOne("KimlikVePersonelServisi.Api.Domain.Entities.Personel", null)
                        .WithOne()
                        .HasForeignKey("KimlikVePersonelServisi.Api.Domain.Entities.Kullanici", "PersonelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KimlikVePersonelServisi.Api.Domain.Entities.Personel", b =>
                {
                    b.HasOne("KimlikVePersonelServisi.Api.Domain.Entities.Departman", null)
                        .WithMany()
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
